### ISSUE TITLE
Branch tracking not working

### ISSUE THREAD

**Issue by lfv89** [olivierverdier/zsh-git-prompt#60]
Hey,

Branch tracking (up and down arrows) are not working, and I don't know why. I tested on different machines (ubuntu and macos) and got the same result. 

When I make a new commit I don't see the UP arrow, and when I have a new remote commit I don't see the down arrow. 

I'm a new zsh user, so maybe I'm missing some basic zsh config? 

Thank you.

**Comment by cmuench** [comment]
It's also not working on my machine. -> Ubuntu 14.04

`$ZSH_THEME_GIT_PROMPT_AHEAD` and `$ZSH_THEME_GIT_PROMPT_BEHIND` variables are set correctly.

**Comment by cmuench** [comment]
In my case i must call "git remote update" to fetch the refs from remote. After that the prompt shows all needed data.

**Comment by olivierverdier** [comment]
What you should do is compare the output of `zsh-git-prompt` with what you get by issuing `git status -sb`. If you see remote information with that command, but not on the prompt, then it's a bug. Otherwise, you have to setup branch tracking correctly for this to work. Feel free to reopen if you are sure that this is a bug.
